services:
  postgres:
    image: postgres:16

    container_name: huellitas-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: huellitas
      POSTGRES_PASSWORD: huellitas123
      POSTGRES_DB: huellitas_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: